-- 코드를 입력하세요
SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIST LEFT JOIN CAR_RENTAL_COMPANY_CAR CAR 
ON HIST.CAR_ID = CAR.CAR_ID
WHERE CAR.CAR_TYPE = '세단' AND DATE_FORMAT(HIST.START_DATE, '%m') = '10'
ORDER BY CAR_ID DESC