SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME FROM (SELECT CATEGORY, PRICE, MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT) A
WHERE PRICE = MAX_PRICE AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC