-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM
(SELECT CATEGORY, PRICE, PRODUCT_NAME, MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICES
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')) A
WHERE PRICE = MAX_PRICES
ORDER BY MAX_PRICE DESC