SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS FROM (SELECT CAR_ID, START_DATE, COUNT(*) OVER (PARTITION BY CAR_ID) AS RENTAL_COUNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31') A
WHERE RENTAL_COUNT >= 5
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC