# SELECT MONTH(START_DATE) AS MONTH, CAR_ID, SUM(NUM_RENT) AS RECORDS
# FROM
# (SELECT CAR_ID, START_DATE, END_DATE, COUNT(*) AS NUM_RENT
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
# GROUP BY CAR_ID
# HAVING NUM_RENT >= 5) A
# GROUP BY MONTH, CAR_ID
# ORDER BY MONTH ASC, CAR_ID DESC

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM 
(SELECT *, COUNT(*) OVER (PARTITION BY CAR_ID) AS NUM_RENT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31') A
WHERE NUM_RENT >=5
GROUP BY MONTH, CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC