SELECT AA.ITEM_ID, AA.ITEM_NAME, AA.RARITY
FROM (SELECT A.ITEM_NAME, A.RARITY, B.PARENT_ITEM_ID, B.ITEM_ID
FROM ITEM_INFO A LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID) AA LEFT OUTER JOIN ITEM_INFO BB ON AA.PARENT_ITEM_ID = BB.ITEM_ID
WHERE BB.RARITY = 'RARE'
ORDER BY AA.ITEM_ID DESC