SELECT AA.ITEM_ID, BB.ITEM_NAME, BB.RARITY
FROM 
(SELECT B.ITEM_ID
FROM ITEM_INFO A LEFT JOIN ITEM_TREE B
ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE RARITY = 'RARE' AND B.ITEM_ID IS NOT NULL) AA
LEFT JOIN ITEM_INFO BB
ON AA.ITEM_ID = BB.ITEM_ID
ORDER BY AA.ITEM_ID DESC