# SELECT STUDENT_NAME, SUBJECT, SCORE
# FROM (SELECT STUDENT_NAME, SUBJECT, SCORE,
#              MIN(SCORE) OVER (PARTITION BY SUBJECT) AS MIN_SCORE
#       FROM SQLD)
# WHERE SCORE = MIN_SCORE;

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV