-- 코드를 작성해주세요
SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM (SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS AVG_LEN
FROM FISH_INFO GROUP BY FISH_TYPE) INFOS
WHERE AVG_LEN >= 33
ORDER BY FISH_TYPE