-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE*SALES_AMOUNT AS SALES
FROM PRODUCT JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT FROM OFFLINE_SALE GROUP BY PRODUCT_ID) A
ON PRODUCT.PRODUCT_ID = A.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC