
SELECT U_BOARD.WRITER_ID AS USER_ID, U_USER.NICKNAME, CONCAT(CITY, ' ', U_USER.STREET_ADDRESS1, ' ', U_USER.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTR(TLNO,1,3),'-',SUBSTR(TLNO,4,4),'-',SUBSTR(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_BOARD U_BOARD JOIN USED_GOODS_USER U_USER
ON U_BOARD.WRITER_ID = U_USER.USER_ID
GROUP BY U_BOARD.WRITER_ID
HAVING COUNT(*) >=3
ORDER BY U_USER.USER_ID DESC
