SELECT CAR_ID, (CASE WHEN SUM(IS_RENTED) != 0 THEN '대여중' ELSE '대여 가능' END) AS AVAILABILITY
FROM (SELECT CAR_ID, (CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1 ELSE 0 END) AS IS_RENTED, START_DATE, END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS RENTED_TABLE
GROUP BY CAR_ID
ORDER BY CAR_ID DESC