SELECT CAR_ID, AVAILABILITY FROM (SELECT *, ROW_NUMBER() OVER (PARTITION BY CAR_ID ORDER BY AVAILABILITY DESC) AS ROWNUM FROM(SELECT CAR_ID, CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) A) AA
WHERE ROWNUM = 1
ORDER BY CAR_ID DESC