SELECT E.AUTHOR_ID, F.AUTHOR_NAME, E.CATEGORY, E.TOTAL_SALES FROM
(SELECT AUTHOR_ID, CATEGORY, SUM(BOOK_TOTAL) AS TOTAL_SALES FROM 
(SELECT B.BOOK_ID, C.CATEGORY, C.AUTHOR_ID, B.SALES_SUM * C.PRICE AS BOOK_TOTAL FROM (SELECT BOOK_ID, SUM(SALES) AS SALES_SUM
FROM (SELECT BOOK_ID, SALES
FROM BOOK_SALES
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01') A
GROUP BY BOOK_ID) B LEFT JOIN BOOK C
ON B.BOOK_ID = C.BOOK_ID) D
GROUP BY AUTHOR_ID, CATEGORY) E
LEFT JOIN AUTHOR F
ON E.AUTHOR_ID = F.AUTHOR_ID 
ORDER BY AUTHOR_ID, CATEGORY DESC