SELECT ID, CASE WHEN CUME_SIZE <= 0.25 THEN 'CRITICAL' WHEN CUME_SIZE <= 0.5 THEN 'HIGH' WHEN CUME_SIZE <= 0.75 THEN 'MEDIUM' ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, CUME_DIST() OVER (ORDER BY SIZE_OF_COLONY DESC) AS CUME_SIZE
FROM ECOLI_DATA) A
ORDER BY ID