SELECT ID, (CASE WHEN SIZE_PER <= 0.25 THEN 'CRITICAL'
            WHEN SIZE_PER <= 0.5 THEN 'HIGH'
            WHEN SIZE_PER <= 0.75 THEN 'MEDIUM'
            ELSE 'LOW' END) AS COLONY_NAME
FROM
(SELECT ID, 1-PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS SIZE_PER
FROM ECOLI_DATA) A
ORDER BY ID