SELECT DEPT.DEPT_ID, DEPT.DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT DEPT JOIN HR_EMPLOYEES EMPL
ON DEPT.DEPT_ID = EMPL.DEPT_ID
GROUP BY DEPT.DEPT_ID, DEPT.DEPT_NAME_EN
ORDER BY AVG_SAL DESC