-- 코드를 입력하세요
# SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES
# FROM BOOK LEFT JOIN BOOK_SALES
# ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
# GROUP BY BOOK.CATEGORY
# HAVING DATE_FORMAT(BOOK_SALES.SALES_DATE, '%Y%m') = "202201"

SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK LEFT JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE,'%Y%m') = '202201'
GROUP BY CATEGORY
ORDER BY CATEGORY