-- 코드를 입력하세요
# SELECT A.REST_ID, A.FOOD_TYPE, A.FAVORITES
# FROM (SELECT *, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES) AS FAV_RANK FROM REST_INFO) A
# WHERE A.FAV_RANK = 1
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM (SELECT *, RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS FAV_RANK FROM REST_INFO) A
WHERE A.FAV_RANK = 1
ORDER BY FOOD_TYPE DESC