SELECT B.ITEM_ID, B.ITEM_NAME, B.RARITY FROM (SELECT B.ITEM_ID
FROM ITEM_TREE A RIGHT JOIN ITEM_TREE B
ON A.PARENT_ITEM_ID = B.ITEM_ID
WHERE A.ITEM_ID IS NULL) A
LEFT JOIN ITEM_INFO B
ON A.ITEM_ID = B.ITEM_ID
ORDER BY B.ITEM_ID DESC