SELECT ID, FISH_NAME, LENGTH
FROM (SELECT A.ID, B.FISH_NAME, A.LENGTH, MAX(A.LENGTH) OVER (PARTITION BY A.FISH_TYPE) AS MAX_LENGTH FROM FISH_INFO A LEFT JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE) AA
WHERE LENGTH = MAX_LENGTH
ORDER BY ID