-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH FROM
(SELECT *, MAX(LENGTH) OVER (PARTITION BY FISH_TYPE) AS MAX_LEN
FROM FISH_INFO) A LEFT JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE LENGTH = MAX_LEN
ORDER BY A.ID