SELECT C.ID FROM (SELECT B.PARENT_ID AS PP, A.PARENT_ID AS P, A.ID
FROM ECOLI_DATA A LEFT JOIN ECOLI_DATA B
ON B.ID = A.PARENT_ID) C LEFT JOIN ECOLI_DATA D
ON D.ID = C.PP
WHERE D.PARENT_ID IS NULL AND C.PP IS NOT NULL